lookupTableAA = [["PHE", "Phenylalanine", "F"],
              ["LEU", "Leucine", "L"],
              ["SER", "Serine", "S"],
              ["TYR", "Tyrosine", "Y"],
              ["stp", "stop", "stp"],
              ["CYS", "Cysteine", "C"],
              ["TRP", "Tryptophan", "W"],
              ["PRO", "Proline", "P"],
              ["HIS", "Histidine", "H"],
              ["GLN", "Glutamine", "Q"],
              ["ARG", "Arginine", "R"],
              ["ILE", "Isoleucine", "I"],
              ["met", "methionine", "m"],
              ["THR", "Threonine", "T"],
              ["ASN", "Asparagine", "N"],
              ["LYS", "Lysine", "K"],
              ["VAL", "Valine", "V"],
              ["ALA", "Alanine", "A"],
              ["ASP", "Aspartic Acid", "D"],
              ["GLU", "Glutamic Acid", "E"],
              ["GLY", "Glycine", "G"]]

lookupTableRNA = [["UUU", "PHE"],
                  ["UUC", "PHE"],
                  ["UUA", "LEU"],
                  ["UUG", "LEU"],
                  ["UCU", "SER"],
                  ["UCC", "SER"],
                  ["UCA", "SER"],
                  ["UCG", "SER"],
                  ["UAU", "TYR"],
                  ["UAC", "TYR"],
                  ["UAA", "stp"],
                  ["UAG", "stp"],
                  ["UGU", "CYS"],
                  ["UGC", "CYS"],
                  ["UGA", "stp"],
                  ["UGG", "TRP"],
                  ["CUU", "LEU"],
                  ["CUC", "LEU"],
                  ["CUA", "LEU"],
                  ["CUG", "LEU"],
                  ["CCU", "PRO"],
                  ["CCC", "PRO"],
                  ["CCA", "PRO"],
                  ["CCG", "PRO"],
                  ["CAU", "HIS"],
                  ["CAC", "HIS"],
                  ["CAA", "GLN"],
                  ["CAG", "GLN"],
                  ["CGU", "ARG"],
                  ["CGC", "ARG"],
                  ["CGA", "ARG"],
                  ["CGG", "ARG"],
                  ["AUU", "ILE"],
                  ["AUC", "ILE"],
                  ["AUA", "ILE"],
                  ["AUG", "met"],
                  ["ACU", "THR"],
                  ["ACC", "THR"],
                  ["ACA", "THR"],
                  ["ACG", "THR"],
                  ["AAU", "ASN"],
                  ["AAC", "ASN"],
                  ["AAA", "LYS"],
                  ["AAG", "LYS"],
                  ["AGU", "SER"],
                  ["AGC", "SER"],
                  ["AGA", "ARG"],
                  ["AGG", "ARG"],
                  ["GUU", "VAL"],
                  ["GUC", "VAL"],
                  ["GUA", "VAL"],
                  ["GUG", "VAL"],
                  ["GCU", "ALA"],
                  ["GCC", "ALA"],
                  ["GCA", "ALA"],
                  ["GCG", "ALA"],
                  ["GAU", "ASP"],
                  ["GAC", "ASP"],
                  ["GAA", "GLU"],
                  ["GAG", "GLU"],
                  ["GGU", "GLY"],
                  ["GGC", "GLY"],
                  ["GGA", "GLY"],
                  ["GGG", "GLY"]]
